 #NAME: Jonathan Chu, Spenser Wong
#EMAIL: jonathanchu78@gmail.com, spenserwong1@gmail.com	
#ID: 004832220, 604766156

.SILENT:

default:
	chmod +x lab3b.sh
	-ln lab3b.sh lab3b
	echo "Compilation Successful"

clean:
	rm -f lab3b *.tar.gz

dist:
	tar -czvf lab3b-004832220.tar.gz Makefile README lab3b.py lab3b.sh