#NAME: Jonathan Chu, Spenser Wong
#EMAIL: jonathanchu78@gmail.com, spenserwong1@gmail.com	
#ID: 004832220, 604766156

.SILENT:

default:
	gcc -g lab3a.c -Wall -Wextra -o lab3a

clean:
	rm -f lab3a *.tar.gz *_.csv

dist:
	tar -czvf lab3a-004832220.tar.gz Makefile README ext2_fs.h lab3a.c
