#NAME: Jonathan Chu
#EMAIL: jonathanchu78@gmail.com
#ID: 004832220

default:
	gcc -Wall -Wextra -g -o lab1a lab1a.c

clean:
	rm -f lab1a *.o *.txt *.tar.gz

dist:
	tar -czvf lab1a-004832220.tar.gz lab1a.c Makefile README

